M48
; DRILL file {KiCad 9.0.0} date 2025-03-02T18:11:57+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-02T18:11:57+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.500
%
G90
G05
T1
X22.525Y-24.188
X22.525Y-67.987
X128.625Y-24.188
X128.625Y-67.888
M30
